### ISSUE TITLE
create a Counter in JavaScript

### ISSUE THREAD

**Issue by SandeepKrSuman** [SandeepKrSuman/project-gallery#10]
- Initailly the counter is 0
- It should have buttons to increase, decrease and reset the value
- counter should not go below 0

Bonus:
- If possible implement a feature where the counter value changes on pressing a specific key on keyboard.

> It's a simple project but you can show your creativity ✨

**Comment by amansingh1373** [comment]
@SandeepKrSuman  i think i can do this kindly assign me this task

**Comment by SandeepKrSuman** [comment]
Sure, go ahead.
Do follow the guidelines and contributing steps.

Key things to keep in mind:
- Create a separate branch
- Create your project folder inside `/public/Projects`
- The html file should be named `index.html`
- When project is completed, take a screen shot or a gif and upload it to `assets` folder by giving proper name.
- Finally your project folder should have a `info.txt` file with required fields (see template for reference)

Happy coding 🚀

**Comment by pratham4434** [comment]
I've already made the PR for this issue. #16 . Please assign me this!

**Comment by SandeepKrSuman** [comment]
@pratham4434 

Everything works in sequential way. It's not the other way round. You are first assigned an issue and then you are supposed to create a PR. Please follow the contributing guidelines. There's no use of wasting your time and effort by blindly creating a PR.

Closing your PR as of now. However you can contribute a new project. In that case too you should create an issue and wait for it to be assigned to you before starting to work upon it.

> I've already made the PR for this issue. #16 . Please assign me this!

**Comment by amansingh1373** [comment]
@SandeepKrSuman created the counter using js kindly have a look at it
![counterproject](https://user-images.githubusercontent.com/67228126/194730694-1874257a-4874-4778-9430-711e136965c7.png)
