### ISSUE TITLE
palindrome number checker

### ISSUE THREAD

**Issue by SandeepKrSuman** [SandeepKrSuman/project-gallery#11]
- Take a number as input from user
- Check whether the input number is a palindromic number of not
- Display appropriate message after checking

> Read about palindromic number [here](https://en.wikipedia.org/wiki/Palindromic_number).

**Comment by vavy06** [comment]
I can do this task. Please assign this issue to me!

**Comment by Uttkarrsh** [comment]
@SandeepKrSuman please assign this task to me.

**Comment by yash-sharma13** [comment]
i will do this one.. please assign this to me

**Comment by SandeepKrSuman** [comment]
Assigning this to @vavy06 on the 'first come first serve' basis.

Do follow the guidelines and contributing steps.

Key things to keep in mind:
- Create a separate branch
- Create your project folder inside `/public/Projects`
- The html file should be named `index.html`
- When project is completed, take a screen shot or a gif and upload it to `assets` folder by giving proper name.
- Finally your project folder should have a `info.txt` file with required fields (see template for reference)

Happy coding 🚀

**Comment by vavy06** [comment]
Hi @SandeepKrSuman !
Please check my PR. This is my first PR. Please reply if anything went wrong.

**Comment by SandeepKrSuman** [comment]
Hey @vavy06 
Start afresh. Create a HTML, CSS and JS file. Follow the contributing steps in the guideline. Those steps are beginner friendly. After doing all that, create a new PR. I've closed the previous one. You need to do everything from start and create a new PR. 

Feel free to ask any question here 🙌
