### ISSUE TITLE
BMI Calculator

### ISSUE THREAD

**Issue by SandeepKrSuman** [SandeepKrSuman/project-gallery#12]
- Take height, weight from user as input
- Calculate the BMI
- Display the calculated BMI
- Also show appropriate message whether it is over weight, under weight, or normal
- You may also add information about the different ranges of BMI

**Comment by Uttkarrsh** [comment]
@SandeepKrSuman please assign me this task.

**Comment by Uttkarrsh** [comment]
Please assign this task to me

**Comment by SandeepKrSuman** [comment]
Assigning this to you @Uttkarrsh 

Do follow the guidelines and contributing steps.

Key things to keep in mind:
- Create a separate branch
- Create your project folder inside `/public/Projects`
- The html file should be named `index.html`
- When project is completed, take a screen shot or a gif and upload it to `assets` folder by giving proper name.
- Finally your project folder should have a `info.txt` file with required fields (see template for reference)

Happy coding 🚀

**Comment by dhirajmishra98** [comment]
I have made an App using flutter

**Comment by SandeepKrSuman** [comment]
That's amazing @dhirajmishra98 !
Unfortunately this repo is for JavaScript projects. If you have any project ideas in JS and want to implement then you are most welcomed. 
Keep coding 🚀 All the best.

**Comment by SandeepKrSuman** [comment]
closing for #27
