### ISSUE TITLE
JS Clock

### ISSUE THREAD

**Issue by ritam077** [SandeepKrSuman/project-gallery#13]

**Comment by ritam077** [comment]
I want to add a clock using java script html css .

**Comment by SandeepKrSuman** [comment]
Sure, go ahead.
Do follow the guidelines and contributing steps.

Key things to keep in mind:
- Create a separate branch
- Create your project folder inside `/public/Projects`
- The html file should be named `index.html`
- When project is completed, take a screen shot or a gif and upload it to `assets` folder by giving proper name.
- Finally your project folder should have a `info.txt` file with required fields (see template for reference)

Happy coding 🚀
