### ISSUE TITLE
Microsoft Logo

### ISSUE THREAD

**Issue by SandeepKrSuman** [SandeepKrSuman/project-gallery#14]
- Create Microsoft logo using CSS
- The word 'Microsoft' should be below the logo
- The word should only be visible when hovered over the logo

Below is an image for reference:

![Screenshot (654)](https://user-images.githubusercontent.com/54541515/194723668-9b2773c4-0241-4c30-ac81-d0c9124413b5.png)

**Comment by parinzee** [comment]
I can work on this! Could you please assign me the issue?

**Comment by SandeepKrSuman** [comment]
Sure, go ahead.
Do follow the guidelines and contributing steps.

Key things to keep in mind:
- Create a separate branch
- Create your project folder inside `/public/Projects`
- The html file should be named index.html
- When project is completed, take a screen shot or a gif and upload it to `assets` folder by giving proper name.
- Finally your project folder should have a `info.txt` file with required fields (see template for reference)

Happy coding 🚀
