### ISSUE TITLE
Tic-Tac-Toe Game

### ISSUE THREAD

**Issue by ishubham010** [SandeepKrSuman/project-gallery#19]
Hello Sandeep, I want to contribute a simple Tic-Tac-Toe or Xs and Os Game.
It will be for two players who take turns marking the spaces in a three-by-three grid with Xs or Os. The player who succeeds in placing three of their marks in a horizontal, vertical, or diagonal row will be the winner.

**Comment by SandeepKrSuman** [comment]
Assigning this to you @ishubham010

Do follow the guidelines and contributing steps.

Key things to keep in mind:
- Create a separate branch
- Create your project folder inside `/public/Projects`
- The html file should be named `index.html`
- When project is completed, take a screen shot or a gif and upload it to `assets` folder by giving proper name.
- Finally your project folder should have a `info.txt` file with required fields (see template for reference)

Happy coding 🚀

**Comment by ishubham010** [comment]
Successfully added Tic Tac Toe Game.
close #24
