### ISSUE TITLE
Beautify README

### ISSUE THREAD

**Issue by SandeepKrSuman** [SandeepKrSuman/project-gallery#2]
There are many sections in README. Your task is to organize the content of README.md file.

---
>
> Fix the typos if there are any and arrange the contents in such a way that looks good and readable.
> You may do necessary changes. 
> For adding any new section in the README, first discuss here by commenting at any point of time.
>

---
- Comment if you want to work on this.
- Wait for it to be assigned to you.
- A beginner contributor is preferable. 
- If you have already contributed, leave this issue for someone who is new.

**Comment by vividxz** [comment]
I would like to work on this.

**Comment by blyncnov** [comment]
I would like to work on this if you assign me

**Comment by SandeepKrSuman** [comment]
Hey @blyncnov this issue is for contributors who are new to open source. I look forward to see you contributing a new JavaScript project in this repo. Happy coding 🚀

**Comment by SandeepKrSuman** [comment]
@vividxz assigning this to you.

**Comment by SandeepKrSuman** [comment]
Hey @vividxz 
It's more than seven days now and I've not heard any thing from you. If you are still willing to work on this issue do let me know ASAP. Else will have to re-assign to someone else.

**Comment by SandeepKrSuman** [comment]
In lack of any response from @vividxz I'm unassigning and making it available for new contributors as a `good first issue`

**Comment by SandeepKrSuman** [comment]
This issue is now open and `up for grab` . Do comment below if some one want to work on this.

**Comment by grow-xd** [comment]
Can i get assigned for it please

**Comment by Lakhaninawaz** [comment]
hello @SandeepKrSuman how it run this code in my vs code please tell me i am first time in!

**Comment by SandeepKrSuman** [comment]
> hello @SandeepKrSuman how it run this code in my vs code please tell me i am first time in!

Hi @Lakhaninawaz to access this repo locally first fork this repo and then clone into your local system. You can use vs code terminal to do so using `git clone <url of forked repo>`. This repo uses REACT.JS to render the gallery. You need to run `npm intall`  and then `npm start` to run the app on localhost:3000. If you need to just view the project without going into the react part you can simply open the index.html file of a project in your browser.

**Comment by SandeepKrSuman** [comment]
Hey @grow-xd I'm assigning this issue to you. This is not a big task so I'm allocating you 2 days to show your progress and we can discuss if you need more time post that. If the progress remains idle post the assigned time I'll have to reassign to someone else. Thanks!

**Comment by grow-xd** [comment]
I will complete this and in given time.
I was thinking of adding 'table of contents', using more emojis and using bulleted list than numbered list.
Thanks!

**Comment by SandeepKrSuman** [comment]
That seems to be a good idea!
Go ahead 🙌🏻

**Comment by grow-xd** [comment]
I have made some changes https://github.com/grow-xd/project-gallery please check.. I will send pull request!!

**Comment by grow-xd** [comment]
I have made some changes..
Please check https://github.com/grow-xd/project-gallery/blob/master/README.md
Tell if any more changes are needed

**Comment by Lakhaninawaz** [comment]
Ok i try to run and after than solve the issues.

**Comment by Lakhaninawaz** [comment]
> > @SandeepKrSuman

Ok i try to run and after than solve the issues.

**Comment by SandeepKrSuman** [comment]
> > > @SandeepKrSuman
> 
> Ok i try to run and after than solve the issues.

This issue is already assigned. Kindly take some other open issue or you can create your own if you have any new idea. Thanks.

**Comment by SandeepKrSuman** [comment]
> I have made some changes.. Please check https://github.com/grow-xd/project-gallery/blob/master/README.md Tell if any more changes are needed

Listing below few changes to consider @grow-xd 
![Screenshot (669)](https://user-images.githubusercontent.com/54541515/197346328-6a3017c7-a69f-4cae-8f1f-8fb2883d3523.png)

1. **Place subheading below the heading and center-aligned.**
2. **align all these tags in one line. Keep center aligned.**

![Screenshot (670)](https://user-images.githubusercontent.com/54541515/197346620-24a8f61e-21e0-4ead-8d00-d481e83cd890.png)

3. **Replace "Programming language" with "Tech Stacks"**
4. **Add React JS tag too after javascript.** If possible, add "React-Bootstrap" too(optional).

**Comment by grow-xd** [comment]
All done please check

**Comment by SandeepKrSuman** [comment]
Looks good! create a PR.
