### ISSUE TITLE
BlackJack Game

### ISSUE THREAD

**Issue by imabhishek02** [SandeepKrSuman/project-gallery#29]
Hello Sandeep, I want to add a Black Jack Game. 
Blackjack is a casino banking game. The most widely played casino banking game in the world, it uses decks of 52 cards and descends from a global family of casino banking games known as Twenty-One.

**Comment by SandeepKrSuman** [comment]
Sure, go ahead.
Do follow the guidelines and contributing steps.

Key things to keep in mind:
- Create a separate branch
- Create your project folder inside `/public/Projects`
- The html file should be named `index.html`
- When project is completed, take a screen shot or a gif and upload it to `assets` folder by giving proper name.
- Finally your project folder should have a `info.txt` file with required fields (see template for reference)

Happy coding 🚀
