### ISSUE TITLE
Add Code of Conduct

### ISSUE THREAD

**Issue by SandeepKrSuman** [SandeepKrSuman/project-gallery#3]
- Create a CODE_OF_CONDUCT.md file in the root of this repo.
- Add guidelines and standard relevant to this project.
  
> Resource : https://www.contributor-covenant.org/version/2/1/code_of_conduct/

---
- This is a 'good first issue'. Someone who is new to contribution is preferred.
- Please leave this issue for beginners if you have already contributed.

**Comment by Valliammai-SM** [comment]
Please assign this to me

**Comment by SandeepKrSuman** [comment]
Hey @Valliammai-SM assigning this to you!
