### ISSUE TITLE
Mouse pointer follower 🐭😾

### ISSUE THREAD

**Issue by SandeepKrSuman** [SandeepKrSuman/project-gallery#37]
**[ Please read carefully ]**

**Who is this project for?**
- Someone who is not here just for `hacktoberfest` PR count.
- Someone with creative mindset. Ready to take up challenges.
- Someone who is ready to learn new things.

**✨ The idea:**
- Let an object follow the mouse pointer.
- Wherever the pointer moves, move the object with respect to(w.r.t) the pointer.

**❌ Already present projects not to be implemented:**
- Eye(s) moving w.r.t. mouse pointer, etc.

**✅ New project idea to implement:**
- Idea based on Tom & Jerry run.
- Let mouse pointer be represented by jerry, the mouse.
- Let there be an object Tom, the cat.
- As soon as the Jerry moves, Tom follows in the same direction.

**Instructions:**
- No need to work on already implemented idea like eye moving along mouse pointer.
- You may add your own flavour and imagination to the above mentioned project idea. **Make it interesting and fun**.
- Project which will be unique will be highly appreciated.
- If you have any new idea which is unique, do comment down below and let's discuss.
- **Start working only if you are assigned this issue.**
- The PR without the assigned issue will be treated as `invalid`.

**Resources:**
1. https://developer.mozilla.org/en-US/docs/Web/API/MouseEvent
2. https://www.w3schools.com/jsref/obj_mouseevent.asp
3. https://css-tricks.com/using-css-cursors/#aa-using-a-custom-cursor-to-enhance-an-element

**Comment by pZacca** [comment]
Hello, @SandeepKrSuman !
I would like to work on this issue.

**Comment by SandeepKrSuman** [comment]
Hi @pZacca 
Hope you have gone through the description of this issue and understand the requirements of the project well.

Assigning this to you !

Do follow the guidelines and contributing steps.

Key things to keep in mind:
- Create a separate branch
- Create your project folder inside `/public/Projects`
- The html file should be named index.html
- When project is completed, take a well cropped screen shot or a gif and upload it to `assets` folder by giving proper name.
- Finally your project folder should have a `info.txt` file with required fields (see template for reference)

Happy coding 🚀
