### ISSUE TITLE
word counter

### ISSUE THREAD

**Issue by SandeepKrSuman** [SandeepKrSuman/project-gallery#38]
- Insert some text in an input box
- Count and show number of words the text have
- Use [text area](https://www.w3schools.com/tags/tag_textarea.asp) tag to insert large text
- You can use your imagination to make this simple project look beautiful

> Only start working if you are assigned this issue.

**Comment by riteshsoni123** [comment]
Hello @SandeepKrSuman I would like to solve this issue.

**Comment by srigundeti10** [comment]
I will take this project

**Comment by de-marauder** [comment]
Hi, I will like to work on this project

**Comment by SandeepKrSuman** [comment]
@riteshsoni123 assigning this to you !

Do follow the guidelines and contributing steps.

Key things to keep in mind:
- Create a separate branch
- Create your project folder inside `/public/Projects`
- The html file should be named `index.html`
- When project is completed, take a screen shot or a gif and upload it to `assets` folder by giving proper name. Make sure that the gif only shows the project rather than capturing whole window/tabs.
- Finally your project folder should have a `info.txt` file with required fields (see template for reference)

Happy coding 🚀

**Comment by SandeepKrSuman** [comment]
Hi @riteshsoni123 It's been almost 2 weeks now and there's no progress shown from your side. As a result I'm marking this issue `open` and available once again.

**Comment by subhashis2204** [comment]
I would like to work on this

**Comment by SandeepKrSuman** [comment]
Hi, following `first come first serve` 

assigning this to @subhashis2204  

Do follow the guidelines and contributing steps.

Key things to keep in mind:
- Create a separate branch
- Create your project folder inside `/public/Projects`
- The html file should be named `index.html`
- When project is completed, take a screen shot or a gif and upload it to `assets` folder by giving proper name. Make sure that the gif only shows the project rather than capturing whole window/tabs.
- Finally your project folder should have a `info.txt` file with required fields (see template for reference)

Happy coding 🚀

**Comment by subhashis2204** [comment]
@SandeepKrSuman I have added the word counter project. Please review the PR.
