### ISSUE TITLE
Add Stopwatch

### ISSUE THREAD

**Issue by charandeep7** [SandeepKrSuman/project-gallery#39]
Features :-

Stopwatch with Dark-mode and responsive view.
With 5 different ringtone when stopwatch count to 0.
Embedded Music for Past time.
With great animation and design.

Can you pls /assign me.

**Comment by SandeepKrSuman** [comment]
Hey @charandeep7 Stop watch is already added in #25

**Comment by SandeepKrSuman** [comment]
closing this as complete in #40
