### ISSUE TITLE
Drum-kit project in javascript

### ISSUE THREAD

**Issue by SandeepKrSuman** [SandeepKrSuman/project-gallery#4]
- Create a Drum-kit in javascript
- The idea is to play an instrument sound when a particular key is pressed on the keyboard.
- Use your imagination to create a beautiful front end along with the funcitonality.
- You can use pictures of different instruments labelled with the key alphabet. This will give appearance of playing that instruement when the labelled key is pressed.

**Comment by aryanayush012** [comment]
I want to contribute , Please assign this to me @SandeepKrSuman

**Comment by SandeepKrSuman** [comment]
Assigning this to you @aryanayush012 . Happy Coding 🚀
