### ISSUE TITLE
create a StopWatch

### ISSUE THREAD

**Issue by SandeepKrSuman** [SandeepKrSuman/project-gallery#5]
- Create a stop watch in JavaScript.
- Include start, pause and reset buttons.

**Comment by whyang0808** [comment]
Hi, I would like to take this.

**Comment by SandeepKrSuman** [comment]
Hey @whyang0808 , assigning this to you.

Please follow the contributing guidelines and contributing steps. 
<https://github.com/SandeepKrSuman/project-gallery#add-a-project>

The README.md is still under editing process, so feel free to ask anything by commenting here.
