### ISSUE TITLE
Round off temperature to 2 decimal places

### ISSUE THREAD

**Issue by SandeepKrSuman** [SandeepKrSuman/project-gallery#55]
**About the project:**
The temperature converter project ---> `public/Project/SwarnitTempConverter` converts the input temperature from one unit to another.

**Issue:**
The converted temperature is more than 10 decimal places long which gives bad readability experience.
![Screenshot (667)](https://user-images.githubusercontent.com/54541515/196890105-88b7c04e-a00d-4c38-a487-d9ef220cd6bb.png)

**To Do:**
Do the changes accordingly so the displayed value is round off to 2 decimal places after conversion.

**Intended file to be changed:**
- `/public/Projects/SwarnitTempConverter/jscript.js`
- **Do not touch or change code of any other file.**

**Run the app for testing:**
- If you are new or have no knowledge of REACT.JS simply open the `index.html` file in your browser to test.

>
>
> **Kindly allow this issue to be taken up by a new contributor/ beginner**
>
>

**Comment by Codefreak69** [comment]
Assign this task to me..
