### ISSUE TITLE
Improve UI of Palindrome checker project.

### ISSUE THREAD

**Issue by Jiya-garg9971** [SandeepKrSuman/project-gallery#58]
![image](https://user-images.githubusercontent.com/100217150/197335180-888a2920-54bf-4aa2-bd6f-f1a76632eabf.png)
After changes

![image](https://user-images.githubusercontent.com/100217150/197335443-a871e482-8fad-4616-a496-4c631a7eff9f.png)

**Comment by Jiya-garg9971** [comment]
Please assign this issue to me.

**Comment by SandeepKrSuman** [comment]
@Jiya-garg9971 Assigning this to you!

**Comment by SandeepKrSuman** [comment]
close as complete in #61
