### ISSUE TITLE
Dark/Light theme toggle 

### ISSUE THREAD

**Issue by Shaba1406** [SandeepKrSuman/project-gallery#60]
I would like to add Dark/light theme toggle for the website.

**Comment by Shaba1406** [comment]
Please Assign this to me. @SandeepKrSuman

**Comment by SandeepKrSuman** [comment]
Hi @Shaba1406 
That's a great idea! 
However I would like to make sure you are comfortable with REACT before you start working on it. ( The website uses REACT.JS to render projects )

Comment down below and I'll be happy to assign this to you after your confirmation.

**Comment by Shaba1406** [comment]
Sorry actually i don't have the knowledge or REACT, I can only do this with the help of css and javascript.

**Comment by SandeepKrSuman** [comment]
It's okay!
Here's one thing that  can be done. You can add the toggle to the existing **Tic-Tac-Toe** project. It uses simple HTML, CSS and JS. 

Take a look at [`/public/Projects/ShubhamTicTacToe`](https://jspgallery.netlify.app/projects/shubhamtictactoe/) and I'll assign if you want to proceed for the same. Thanks!

**Comment by iampitrus** [comment]
Hi @SandeepKrSuman kindly assign it to me

**Comment by SandeepKrSuman** [comment]
Hi, I'm planning a website improvement window in near future. It will be a good idea to open this issue then. Thanks!
