### ISSUE TITLE
Make the existing Palindrome Checker responsive

### ISSUE THREAD

**Issue by SandeepKrSuman** [SandeepKrSuman/project-gallery#62]
The project is present at: `/public/Projects/VaibhavPalindromeCheck`

- On large screens everything looks fine.
- However, in mobile view the main content of the project is scrolled towards the right of the screen.
- Your task is to make the project responsive so that the input box and button remains in the center on smaller screens.

**intended file to be changed:**
- `/public/Projects/VaibhavPalindromeCheck/index.html`
- You may add a `.css` file inside `/public/Projects/VaibhavPalindromeCheck` if you want
- All other files should remain unchanged before commiting

**Comment by LucianeFernandesRoque** [comment]
assigne me the issue please @SandeepKrSuman

**Comment by SandeepKrSuman** [comment]
Assigning this to you @LucianeFernandesRoque !
