### ISSUE TITLE
A JS mini project!

### ISSUE THREAD

**Issue by tech-with-aditya** [SandeepKrSuman/project-gallery#7]
Hi! Sandeep, I wanted to add a JS mini 'Modal Window' project in your repo to contribute to open source and hactoberfest.

**Comment by SandeepKrSuman** [comment]
Sure, go ahead.
Do follow the guidelines and contributing steps.

Key things to keep in mind:
- Create a separate branch
- Create your project folder inside `/public/Projects`
- The html file should be named index.html
- When project is completed, take a screen shot or a gif and upload it to `assets` folder by giving proper name.
- Finally your project folder should have a `info.txt` file with required fields (see template for reference)

Happy coding 🚀
