### ISSUE TITLE
Customize the scroll bar

### ISSUE THREAD

**Issue by zugzwang03** [SandeepKrSuman/project-gallery#84]
I want to customize the scrollbar of the website to fit it well with the rest of its design.
Can I make this contribution under Hacktoberfest'22 ?

**Comment by SandeepKrSuman** [comment]
Hey @zugzwang03 the website is rendered using **REACT.JS** .
Just want to make sure you are comfortable using React before assigning this to you!

**Comment by zugzwang03** [comment]
Yes I am comfortable.  I did this thing before.

**Comment by SandeepKrSuman** [comment]
Great! then go ahead 🚀

**Comment by IM-TECHNO** [comment]
It has aleady been assigned @siddhesh-coder . Maybe try doing any other contribution to the same repository with a new issue.

It was just my opinion but it's totally up to you and @SandeepKrSuman

**Comment by SandeepKrSuman** [comment]
> It has aleady been assigned @siddhesh-coder . Maybe try doing any other contribution to the same repository with a new issue.
> 
> It was just my opinion but it's totally up to you and @SandeepKrSuman

**True that!**

**Comment by SandeepKrSuman** [comment]
closing in #87
